#define TORQUE_LC_DT 4
#define TORQUE_LC_SCK 5
#define THRUST_LC_DT 6
#define THRUST_LC_SCK 7

#define TORQUE_LC_CALVAL 828.58
#define THRUST_LC_CALVAL -400.00

#define STABILIZING_TIME 2000.0 
#define EXECUTE_TARE TRUE